# Site settings
title: Your awesome title
email: burak.gunhan@med.uni-goettingen.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://gunhanb.github.io/blog/" # the base hostname & protocol for your site
github_username:  gunhanb
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
