# Site settings
title: Burak's Personal Blog
email: burakgunhan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is just another blog about statistics, R and data science etc.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://gunhanb.github.io/blog/" # the base hostname & protocol for your site
github_username:  gunhanb
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
