# Site settings
title: Just another personal blog
email: burak.gunhan@med.uni-goettingen.de
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://gunhanb.github.io/blog/" # the base hostname & protocol for your site
github_username:  gunhanb
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
